"""
BRD Agent - Professional PDF Generator
========================================
Generates high-quality PDF reports for the extracted BRD.
Uses fpdf2 for a lightweight, premium layout.
"""

from fpdf import FPDF
import datetime
import json
import os

class BRDPDFGenerator(FPDF):
    def header(self):
        # Premium Header with Logo (simulated with text if no logo)
        self.set_font("Arial", "B", 15)
        self.set_text_color(26, 31, 113) # Dark Blue
        self.cell(0, 10, "BRD AGENT - PROFESSIONAL REQUIREMENTS REPORT", 0, 1, "C")
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, "R")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | Confidential | Generated by AI Business Analyst", 0, 0, "C")

    def generate_report(self, brd_data, output_path):
        self.add_page()
        
        # 1. Project Overview
        self.set_font("Arial", "B", 14)
        self.set_text_color(50, 50, 50)
        self.cell(0, 10, f"Project: {brd_data.get('project_topic', 'Unnamed Project')}", 0, 1, "L")
        self.ln(5)

        # 2. Project Health
        health = brd_data.get("project_health_score", 100)
        self.set_font("Arial", "B", 12)
        health_color = (0, 150, 0) if health > 70 else (150, 150, 0) if health > 40 else (150, 0, 0)
        self.set_text_color(*health_color)
        self.cell(0, 10, f"Current Project Health Score: {health}%", 0, 1, "L")
        self.ln(5)

        # 3. Requirements (The Core)
        self.set_font("Arial", "B", 13)
        self.set_text_color(26, 31, 113)
        self.cell(0, 10, "1. Functional & Non-Functional Requirements", 0, 1, "L")
        self.set_font("Arial", "", 10)
        self.set_text_color(0)
        
        reqs = brd_data.get("requirements", [])
        for req in reqs:
            if isinstance(req, dict):
                text = f"[{req.get('id', 'REQ')}] {req.get('text', '')}"
                source = f"(Source: {req.get('source', 'N/A')})"
                self.multi_cell(0, 7, f"- {text} {source}", 0, "L")
            else:
                self.multi_cell(0, 7, f"- {req}", 0, "L")
        self.ln(5)

        # 4. Stakeholders & Sentiment
        self.set_font("Arial", "B", 13)
        self.set_text_color(26, 31, 113)
        self.cell(0, 10, "2. Stakeholder Analysis & Sentiment", 0, 1, "L")
        self.set_font("Arial", "", 10)
        self.set_text_color(0)
        
        stakeholders = brd_data.get("stakeholders", [])
        for s in stakeholders:
            name = s.get("name", "N/A")
            role = s.get("role", "N/A")
            sentiment = s.get("sentiment", "Neutral")
            self.multi_cell(0, 7, f"- {name} ({role}) | Sentiment: {sentiment.upper()}", 0, "L")
        self.ln(5)

        # 5. Decisions
        self.set_font("Arial", "B", 13)
        self.set_text_color(26, 31, 113)
        self.cell(0, 10, "3. Key Decisions", 0, 1, "L")
        self.set_font("Arial", "", 10)
        self.set_text_color(0)
        for dec in brd_data.get("decisions", []):
            if isinstance(dec, dict):
                self.multi_cell(0, 7, f"- {dec.get('text', '')} (Ref: {dec.get('source', 'N/A')})", 0, "L")
            else:
                self.multi_cell(0, 7, f"- {dec}", 0, "L")
        self.ln(5)

        # 6. Conflicts
        if brd_data.get("conflicts"):
            self.set_font("Arial", "B", 13)
            self.set_text_color(150, 0, 0)
            self.cell(0, 10, "4. Conflict Alerts !!!", 0, 1, "L")
            self.set_font("Arial", "", 10)
            self.set_text_color(0)
            for c in brd_data.get("conflicts", []):
                desc = c.get("description", "") if isinstance(c, dict) else c
                self.multi_cell(0, 7, f"- ⚠️ {desc}", 0, "L")

        self.output(output_path)
        return output_path

def export_brd_to_premium_pdf(brd_data, filename="BRD_Report.pdf"):
    """Convenience function to export BRD."""
    pdf = BRDPDFGenerator()
    return pdf.generate_report(brd_data, filename)
